---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.1
    app.quarkus.io/commit-id: 25505de24f6f284c72e4a7460df14595fb743465
    app.quarkus.io/vcs-uri: https://github.com/lordofthejars/event-driven-ai.git
    app.quarkus.io/build-timestamp: 2024-03-05 - 11:48:56 +0000
  labels:
    app.kubernetes.io/name: text-sentiment-djl
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: text-sentiment-djl
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: text-sentiment-djl
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.1
    app.quarkus.io/commit-id: 25505de24f6f284c72e4a7460df14595fb743465
    app.quarkus.io/vcs-uri: https://github.com/lordofthejars/event-driven-ai.git
    app.quarkus.io/build-timestamp: 2024-03-05 - 11:48:56 +0000
  labels:
    app.kubernetes.io/name: text-sentiment-djl
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: text-sentiment-djl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: text-sentiment-djl
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.8.1
        app.quarkus.io/commit-id: 25505de24f6f284c72e4a7460df14595fb743465
        app.quarkus.io/vcs-uri: https://github.com/lordofthejars/event-driven-ai.git
        app.quarkus.io/build-timestamp: 2024-03-05 - 11:48:56 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: text-sentiment-djl
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/hgrahsl/eda-ai-quarkus-sentiment-service:1.0.3-SNAPSHOT-amd64
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: text-sentiment-djl
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
