---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.1
    app.quarkus.io/commit-id: e87492e27c4944bda2d39ed17865ed4f5fd559dd
    app.quarkus.io/vcs-uri: https://github.com/lordofthejars/event-driven-ai.git
    app.quarkus.io/build-timestamp: 2024-03-04 - 19:32:47 +0000
  labels:
    app.kubernetes.io/name: text-sentiment-djl
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: text-sentiment-djl
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: text-sentiment-djl
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.1
    app.quarkus.io/commit-id: e87492e27c4944bda2d39ed17865ed4f5fd559dd
    app.quarkus.io/vcs-uri: https://github.com/lordofthejars/event-driven-ai.git
    app.quarkus.io/build-timestamp: 2024-03-04 - 19:32:47 +0000
  labels:
    app.kubernetes.io/name: text-sentiment-djl
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: text-sentiment-djl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: text-sentiment-djl
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.8.1
        app.quarkus.io/commit-id: e87492e27c4944bda2d39ed17865ed4f5fd559dd
        app.quarkus.io/vcs-uri: https://github.com/lordofthejars/event-driven-ai.git
        app.quarkus.io/build-timestamp: 2024-03-04 - 19:32:47 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: text-sentiment-djl
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/lordofthejars/text-sentiment-djl:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: text-sentiment-djl
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
